[package]
name = "create_texture_atlas"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = {version="4.4.12", features=["derive"]}
env_logger = "0.10.2"
log = "0.4.20"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]
