[package]
name = "package_assets"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = {version="4.4.12", features=["derive"]}
env_logger = "0.10.2"
flate2 = "1.0.28"
glob = "0.3.1"
log = "0.4.20"
tar = "0.4.40"
